# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7647b8e01b313ff00066aeeba28c32c3f2b3c681231c20e0c5ddae1001df370af576e680ebd1eef6177d102d817ea5af9e4ba47ef085b7715caaebe8ae4a8cfd

test:
  secret_key_base: 8301d93d8867b77810a8ca2cb5b44c5506b352246c47e19533bfc1567272a6632af0fad5960e4faf97a36fd34ef8bbb50015247426ff44f079a4bcb937f79496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
